spring.application.name=timelymd-api

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db.pxoarhqeewkoocoqnocs.supabase.co:5432/postgres?user=${DB_USERNAME}&password=${DB_PASSWORD}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update