spring.application.name=timelymd-api

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db.pxoarhqeewkoocoqnocs.supabase.co:5432/postgres?user=${DB_USERNAME}&password=${DB_PASSWORD}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SUPABASE_API_URL}}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SUPABASE_JWKS_URL}}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

server.port=3000

